controller_manager_ns: controller_manager
controller_list:
  - name: torso_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - torso_1_joint
      - torso_2_joint
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
  - name: head_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - head_1_joint
      - head_2_joint
  - name: left_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - hand_left_index_joint
      - hand_left_middle_joint
      - hand_left_thumb_joint
      # Added for MoveIt!
      - hand_left_index_1_joint
      - hand_left_index_2_joint
      - hand_left_index_3_joint
      - hand_left_middle_1_joint
      - hand_left_middle_2_joint
      - hand_left_middle_3_joint
  - name: right_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - hand_right_index_joint
      - hand_right_middle_joint
      - hand_right_thumb_joint
       # Added for MoveIt!
      - hand_right_index_1_joint
      - hand_right_index_2_joint
      - hand_right_index_3_joint
      - hand_right_middle_1_joint
      - hand_right_middle_2_joint
      - hand_right_middle_3_joint
