joint_limits:
  arm_right_7_joint:
    has_velocity_limits: true
    max_velocity: &max_vel 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_left_middle_1_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_left_index_2_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_left_middle_2_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  leg_left_4_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  leg_left_1_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_left_middle_3_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_right_index_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  leg_right_2_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_right_2_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_right_4_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  leg_left_3_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  leg_right_6_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_right_1_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_right_3_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_left_2_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  leg_right_5_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  leg_right_4_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  leg_right_3_joint:
    has_velocity_limits: true
    max_velocity: *max_vel
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_left_middle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_right_index_1_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_left_thumb_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_left_1_joint:
    has_velocity_limits: true
    max_velocity: 5.4
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_right_middle_2_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_right_index_3_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1.0
  head_1_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_right_middle_3_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_right_5_joint:
    has_velocity_limits: true
    max_velocity: 1.77
    has_acceleration_limits: true
    max_acceleration: 1.0
  leg_right_1_joint:
    has_velocity_limits: true
    max_velocity: 2.35
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_right_6_joint:
    has_velocity_limits: true
    max_velocity: 1.77
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_left_5_joint:
    has_velocity_limits: true
    max_velocity: 1.77
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_right_thumb_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1.0
  head_2_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_left_6_joint:
    has_velocity_limits: true
    max_velocity: 1.77
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_left_index_1_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_left_index_3_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_left_7_joint:
    has_velocity_limits: true
    max_velocity: 1.77
    has_acceleration_limits: true
    max_acceleration: 1.0
  torso_1_joint:
    has_velocity_limits: true
    max_velocity: 5.4
    has_acceleration_limits: true
    max_acceleration: 1.0
  torso_2_joint:
    has_velocity_limits: true
    max_velocity: 5.4
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_right_middle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_left_3_joint:
    has_velocity_limits: true
    max_velocity: 5.15
    has_acceleration_limits: true
    max_acceleration: 1.0
  leg_left_6_joint:
    has_velocity_limits: true
    max_velocity: 2.27
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_left_index_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1.0
  leg_left_5_joint:
    has_velocity_limits: true
    max_velocity: 2.44
    has_acceleration_limits: true
    max_acceleration: 1.0
  leg_left_2_joint:
    has_velocity_limits: true
    max_velocity: 2.27
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_left_4_joint:
    has_velocity_limits: true
    max_velocity: 5.15
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_right_index_2_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_right_middle_1_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1.0
